name: build-and-push

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set the Docker version tag
        run: |
          REF_NAME=${{ github.ref_name }}
          DOCKER_VERSION_TAG=${REF_NAME:1}
          echo "DOCKER_VERSION_TAG=$DOCKER_VERSION_TAG" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: will2hew/docmost:${{  env.DOCKER_VERSION_TAG }}
